algoritmo "Lista 01 - questão 02"
// Função : Somar duas notas e calcula a média
// Autor : Daniel Santos
// Data : 21/03/2019
// Seção de Declarações 
var
   nota1, nota2, media: real
inicio
// Seção de Comandos

//Entrada de dados
   escreva("Entre com a nota 1: ")
   leia(nota1)
   
   escreva("Entre com a nota 2: ")
   leia(nota2)
   
//Processamento de dados
   media <- (nota1 + nota2)/2
   
   escreva("A média do aluno é: ", media)

fimalgoritmo
